### ISSUE TITLE
ACR in kubernetes cluster 

### ISSUE THREAD

**Issue by remi-cogito** [Azure/acr#725]
**Describe the bug**
I want to set up connected registry in my kubernetes cluster so I fallow this https://github.com/Azure/acr/blob/main/docs/preview/connected-registry/quickstart-deploy-connected-registry-kubernetes.md but I am getting  413 Request Entity Too Large error and have no clue why.
Error:
```
root@k3s-server:~# kubectl -n connected-registry logs connected-registry-64bc779cd-ddp9l 
[2023-12-13T18:50:36Z INFO  supervisor] starting command 'dotnet' with args: ["/bin/ACR.OnPrem.FrontEnd.dll"]
[2023-12-13T18:50:36Z INFO  supervisor] starting command 'registry' with args: ["serve", "/etc/acr/config.yml"]
[INFO] 2023-12-13T18:50:36Z [AcrBackendEvent] OperationName: ConfigureLogging, Message: Logging level set to: info
[2023-12-13T18:50:36Z INFO  supervisor] all commands started successfully
[INFO] 2023-12-13T18:50:36Z [AcrBackendEvent] OperationName: ListenAndServe, Message: listening on 127.0.0.1:5000
[INFO] 2023-12-13T18:50:37Z [AcrOperationEvent] OperationName: ActivateAsync, CorrelationId: 66cfeb74-a48a-49ca-a727-f07487f14875, Message: Attempting to activate connected registry 'portalrwtesting1'
Startup of 'FrontEnd' failed with error: 'Failed to activate the connected registry instance. The request failed with status: RequestEntityTooLarge, correlationId: '66cfeb74-a48a-49ca-a727-f07487f14875', Response: '<html>
<head><title>413 Request Entity Too Large</title></head>
<body bgcolor="white">
<center><h1>413 Request Entity Too Large</h1></center>
<hr><center>openresty</center>
</body>
</html>
''
[2023-12-13T18:50:39Z ERROR supervisor] process 'dotnet /bin/ACR.OnPrem.FrontEnd.dll' has terminated, breaking out of monitor loop
[2023-12-13T18:50:39Z INFO  supervisor] shutting down all child processes
[2023-12-13T18:50:39Z WARN  supervisor] sending shutdown signal to 'registry serve /etc/acr/config.yml'
[2023-12-13T18:50:39Z INFO  supervisor] successfully sent a shutdown signal to 'registry serve /etc/acr/config.yml'
[2023-12-13T18:50:39Z INFO  supervisor] all child processes have shutdown
Error: exiting because a child process terminated
```
**To Reproduce**
1. https://github.com/Azure/acr/blob/main/docs/preview/connected-registry/quickstart-deploy-connected-registry-kubernetes.md

**Expected behavior**
It should connect to registry.

**Any relevant environment information**
 - OS: DISTRIB_ID=Ubuntu
          DISTRIB_RELEASE=22.04
          DISTRIB_CODENAME=jammy
          DISTRIB_DESCRIPTION="Ubuntu 22.04.3 LTS"
 - Azure CLI: 2.55.0
 - Kubernetes: v1.27.7+k3s1

**Additional context**
That is for http set up. For https I am getting: 
```
[2023-12-13T19:19:05Z INFO  supervisor] starting command 'ACR.OnPrem.FrontEnd' with args: []
[2023-12-13T19:19:05Z INFO  supervisor] starting command 'registry' with args: ["serve", "/etc/acr/config.yml"]
[2023-12-13T19:19:05Z INFO  supervisor] all commands started successfully
[INFO] 2023-12-13T19:19:05Z [AcrBackendEvent] OperationName: ConfigureLogging, Message: Logging level set to: info
[INFO] 2023-12-13T19:19:05Z [AcrBackendEvent] OperationName: ListenAndServe, Message: listening on 127.0.0.1:5000
[INFO] 2023-12-13T19:19:10Z [AcrOperationEvent] OperationName: ActivateAsync, CorrelationId: 9092e9f7-2963-4926-84b3-7a9fb85917cd, Message: Attempting to activate connected registry 'portalrwtesting1'
Startup of 'FrontEnd' failed with exception ACR.OnPrem.Common.Exceptions.RetryableException: Failed to activate the connected registry instance. The request failed with status: InternalServerError, correlationId: '9092e9f7-2963-4926-84b3-7a9fb85917cd'
   at ACR.OnPrem.FrontEnd.Services.ActivationService.ValidateResponseAsync(String correlationId, HttpResponseMessage response)
   at ACR.OnPrem.FrontEnd.Services.ActivationService.InvokeActivateRequestAsync(String connectedRegistryName, String activationId, String correlationId, CancellationToken cancellationToken)
   at ACR.OnPrem.FrontEnd.Services.ActivationService.ActivateAsync(String activationFilePath, String activationId, CancellationToken cancellationToken)
   at ACR.OnPrem.FrontEnd.Services.ActivationService.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at ACR.OnPrem.FrontEnd.Program.Main(String[] args)
[2023-12-13T19:19:11Z ERROR supervisor] process 'ACR.OnPrem.FrontEnd' has terminated, breaking out of monitor loop
[2023-12-13T19:19:11Z INFO  supervisor] shutting down all child processes
[2023-12-13T19:19:11Z WARN  supervisor] sending shutdown signal to 'registry serve /etc/acr/config.yml'
[2023-12-13T19:19:11Z INFO  supervisor] successfully sent a shutdown signal to 'registry serve /etc/acr/config.yml'
[2023-12-13T19:19:11Z INFO  supervisor] all child processes have shutdown
Error: exiting because a child process terminated
```
And there is nothing in Azure logs
If any information is a concern to post here, you can create a [support ticket](https://azure.microsoft.com/en-us/support/create-ticket/) or send an email to acrsup@microsoft.com.

**Comment by terencet-dev** [comment]
Hi @remi-cogito, apologies for the delay here. Have you opened a [support ticket](https://learn.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request) for this yet?

**Comment by jamesdelbridge** [comment]
Hi @remi-cogito, did you get this resolved as I am having the same issue trying to follow the same github guide.

"Startup of 'FrontEnd' failed with error: 'Failed to activate the connected registry instance. The request failed with status: NotFound"

**Comment by getk12** [comment]
Hi @jamesdelbridge @remi-cogito, following up if you still require assistance with connected registry. If so, would be happy to also understand the deployment model you are using.

**Comment by getk12** [comment]
Closing as no response for some time. Please share further details if assistance is still needed.
